version: '3'
services:
  database:
    image: postgres:latest
    env_file:
      - database.env
    ports:
      - '5432:5432'
    volumes:
      - /data/db:/var/lib/postgresql/data
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/src/app
    tty: true
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - database
